### ISSUE TITLE
Fix server type error on front

### ISSUE THREAD

**Issue by Diana-Cherry-8** [Waiviogit/waivio#6118]
SSR error occured, falling back to bundled application instead TypeError: Cannot read properties of undefined (reading 'map')
2023-11-10T11:41:06.077259476Z     at Lt (/usr/src/app/build/server.js:1:525738)
2023-11-10T11:41:06.077262973Z     at combination (/usr/src/app/node_modules/redux/lib/redux.js:568:29)
2023-11-10T11:41:06.077265873Z     at dispatch (/usr/src/app/node_modules/redux/lib/redux.js:296:22)
2023-11-10T11:41:06.077268240Z     at /usr/src/app/node_modules/connected-react-router/lib/middleware.js:33:18
2023-11-10T11:41:06.077270536Z     at /usr/src/app/node_modules/redux-thunk/lib/index.js:27:16
2023-11-10T11:41:06.077272840Z     at /usr/src/app/node_modules/redux-promise-middleware/dist/index.js:95:26
2023-11-10T11:41:06.077275086Z     at /usr/src/app/build/server.js:383:231025
2023-11-10T11:41:06.077277259Z     at dispatch (/usr/src/app/node_modules/redux/lib/redux.js:699:28)
2023-11-10T11:41:06.077279446Z     at handleFulfill (/usr/src/app/node_modules/redux-promise-middleware/dist/index.js:183:11)
2023-11-10T11:41:06.077281868Z     at runMicrotasks (<anonymous>)
2023-11-10T11:41:06.077284561Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-11-10T11:41:06.077286933Z     at async Promise.all (index 5)
2023-11-10T11:41:06.077289180Z     at async Promise.all (index 1)

SSR error occured, falling back to bundled application instead TypeError: i.map is not a function
2023-11-10T11:41:32.205324241Z     at j (/usr/src/app/build/server.js:137:33740)
2023-11-10T11:41:32.205329188Z     at o (/usr/src/app/build/server.js:383:11101)
2023-11-10T11:41:32.205332846Z     at je (/usr/src/app/build/server.js:383:12119)
2023-11-10T11:41:32.205336538Z     at e.t.render (/usr/src/app/build/server.js:383:14640)
2023-11-10T11:41:32.205340180Z     at e.t.read (/usr/src/app/build/server.js:383:14216)
2023-11-10T11:41:32.205352437Z     at renderToString (/usr/src/app/build/server.js:383:19829)
2023-11-10T11:41:32.205356078Z     at /usr/src/app/build/server.js:383:484198
2023-11-10T11:41:32.205359778Z     at m (/usr/src/app/build/server.js:383:24006)
2023-11-10T11:41:32.205367196Z     at Generator.<anonymous> (/usr/src/app/build/server.js:383:25336)
2023-11-10T11:41:32.205371648Z     at Generator.next (/usr/src/app/build/server.js:383:24431)
2023-11-10T11:41:32.205375297Z     at n (/usr/src/app/build/server.js:1:119959)
2023-11-10T11:41:32.205378951Z     at i (/usr/src/app/build/server.js:1:120169)
2023-11-10T11:41:32.205386908Z     at runMicrotasks (<anonymous>)
2023-11-10T11:41:32.205391117Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Nasirahamad88** [comment]
There are two different errors in the logs related to your server-side rendering (SSR) in a JavaScript application.
